import { StoredEmbedding, MatchResult } from '../../types/recognition';
import { deserializeEmbedding } from './EmbeddingSerializer';
import { RECOGNITION_THRESHOLD } from '../../utils/constants';

/**
 * Computes the Cosine Similarity between two 128-dimensional vectors.
 * 
 * ============================================================================
 * MATHEMATICAL BREAKDOWN & OPTIMIZATION
 * ============================================================================
 * 
 * Cosine Similarity measures the cosine of the angle θ between two non-zero vectors 
 * A and B in an inner product space. It is calculated as:
 * 
 *                       A · B            ∑ (A_i * B_i)
 *    similarity = ----------------- = -----------------------
 *                   ||A|| * ||B||     √(∑ A_i^2) * √(∑ B_i^2)
 * 
 * Where:
 * - A · B is the dot product of vectors A and B.
 * - ||A|| and ||B|| represent the L2 Euclidean norms (magnitudes) of the vectors.
 * 
 * Optimization Trick:
 * The embedding vectors generated by MobileFaceNet are pre-normalized to have an 
 * L2-norm of exactly 1.0 (unit vectors), meaning:
 *    ||A|| = 1.0   and   ||B|| = 1.0
 * 
 * Consequently, the denominator (||A|| * ||B||) is 1.0 * 1.0 = 1.0. 
 * This simplifies the formula to a simple dot product, eliminating expensive square root
 * and division operations for every vector comparison:
 * 
 *    similarity = A · B = ∑_{i=1}^{128} (A_i * B_i)
 * 
 * This allows the similarity computation to be extremely light, consisting only of 128
 * float multiplications and additions per candidate.
 * 
 * ============================================================================
 * COMPLEXITY & PERFORMANCE ANALYSIS FOR 5,000 CANDIDATES
 * ============================================================================
 * 
 * When querying a database of 5,000 users offline:
 * - Dimension (D) = 128 float coordinates.
 * - Number of candidates (N) = 5,000.
 * - Total float calculations per scan = N * D = 5,000 * 128 = 640,000 operations.
 * 
 * Modern JavaScript execution engines (Hermes on React Native, V8 on Android, JSC on iOS) 
 * are highly optimized for linear array traversals and can execute 640,000 multiply-accumulate 
 * operations in less than 2ms.
 * 
 * Because of this sub-millisecond execution:
 * 1. Brute-force linear scanning is preferred over spatial indexing (e.g., k-d trees, HNSW).
 * 2. It avoids index rebuild overheads and database fragmentation during new enrollments.
 * 3. It runs entirely in-memory with constant-time memory overhead.
 * 4. It maintains O(N) search times that easily satisfy the Datalake requirements (< 50ms latency).
 */
export function computeCosineSimilarity(vectorA: Float32Array, vectorB: Float32Array): number {
  if (vectorA.length !== 128 || vectorB.length !== 128) {
    throw new Error(`INVALID_INPUT: Expected vectors of length 128, got A:${vectorA.length}, B:${vectorB.length}`);
  }

  let dotProduct = 0;
  for (let i = 0; i < 128; i++) {
    dotProduct += vectorA[i] * vectorB[i];
  }

  return dotProduct;
}

/**
 * Scans a list of stored candidate face embeddings to find the best match for the probe embedding.
 * Returns a MatchResult indicating success/failure, matched user ID, similarity confidence, and match latency.
 */
export function matchEmbedding(
  probeEmbedding: Float32Array,
  candidates: StoredEmbedding[],
  threshold: number = RECOGNITION_THRESHOLD
): MatchResult {
  const startTime = Date.now();
  
  let bestMatchUserId: string | null = null;
  let highestSimilarity = -1;

  try {
    // 1. Loop through all candidates sequentially (linear scan / brute force)
    for (let i = 0; i < candidates.length; i++) {
      const candidate = candidates[i];
      
      // Deserialize binary blob (512 bytes) back to Float32Array (128 floats)
      const candidateVector = deserializeEmbedding(candidate.embeddingBlob);
      
      // Compute similarity score
      const similarity = computeCosineSimilarity(probeEmbedding, candidateVector);

      // Track the candidate with the highest similarity score
      if (similarity > highestSimilarity) {
        highestSimilarity = similarity;
        bestMatchUserId = candidate.userId;
      }
    }

    const elapsedMs = Date.now() - startTime;
    const isMatched = highestSimilarity >= threshold;

    return {
      matched: isMatched,
      userId: isMatched ? bestMatchUserId : null,
      confidence: highestSimilarity,
      matchTimeMs: elapsedMs,
    };
  } catch (error) {
    console.error('[EmbeddingMatcher] Error during embedding matching:', error);
    
    return {
      matched: false,
      userId: null,
      confidence: 0,
      matchTimeMs: Date.now() - startTime,
    };
  }
}
